export const NEXT_PUBLIC_BACKEND_URL = `http://localhost:8010`; // If you are following the instructions in `https://github.com/soroswap/core`
export const NEXT_PUBLIC_SOROSWAP_BACKEND_URL = `https:`; //api.soroswap.finance/ Your local soroswap backend url
export const NEXT_PUBLIC_SOROSWAP_BACKEND_ENABLED = false; // Enables or disables the soroswap backend
export const NEXT_PUBLIC_DEFAULT_NETWORK = 'standalone'; // The default network to connect
export const NEXT_PUBLIC_AGGREGATOR_ENABLED = false; // Enables or disables the aggregator
export const NEXT_PUBLIC_SOROSWAP_BACKEND_API_KEY = 'BACKEND_API_KEY'; // The API key to autenthicate in the soroswap backend
export const NEXT_PUBLIC_TRUSTLINE_WALLET_PUBLIC_KEY = 'STELLAR_PUBLIC_KEY'; // The public key of the trustline wallet
export const NEXT_PUBLIC_TEST_TOKENS_ADMIN_SECRET_KEY = 'STELLAR_SECRET_KEY'; // The secret key of the test tokens admin

export const NEXT_PUBLIC_BACKSTOP = 'CCWSNUZAIKPGWQ7KIGVFJUNCFC4JP4AOP4FJCWB4OZ3QC6CGWFRFKG5J';
export const NEXT_PUBLIC_BACKSTOP_V2 = 'CANQKUZ6P4AVTLMVXWPGPIBE2J2VK6LFIELAP2HULGB2XU5HBGYCM5WL';
export const NEXT_PUBLIC_POOL = 'CC7OVK4NABUX52HD7ZBO7PQDZEAUJOH55G6V7OD6Q7LB6HNVPN7JYIEU';
export const NEXT_PUBLIC_COLLATERAL_ASSET = 'CBZFW4ICZQY6WUKDI2EFRGKICT36QTLHZGS7BZTGJQ7RHCA2OTLO2PNM';
export const NEXT_PUBLIC_STABLECOIN_ASSET = 'CDJMJFAYTGWQXH27SBU6HJKBZ2YKFKQWOKY43LDQWRBH3HTVELG4LISO';
export const NEXT_PUBLIC_ROUTER_ID = 'CC6WRJYMZA574TOXNO2ZWU4HIXJ5OLKGB7JF556RKMZPSV2V62SLBTPK';

export const NEXT_PUBLIC_USDC_ISSUER = 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56';
export const NEXT_PUBLIC_BLND_ISSUER = 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56';

export const NEXT_PUBLIC_PASSPHRASE = undefined
export const NEXT_PUBLIC_STELLAR_EXPERT_URL = undefined
export const  NEXT_PUBLIC_RPC_URL = undefined
export const NEXT_PUBLIC_HORIZON_URL = undefined