export const NEXT_PUBLIC_BACKEND_URL = `http://localhost:8010`; // If you are following the instructions in `https://github.com/soroswap/core`
export const NEXT_PUBLIC_SOROSWAP_BACKEND_URL = `https:`; //api.soroswap.finance/ Your local soroswap backend url
export const NEXT_PUBLIC_SOROSWAP_BACKEND_ENABLED = false; // Enables or disables the soroswap backend
export const NEXT_PUBLIC_DEFAULT_NETWORK = 'standalone'; // The default network to connect
export const NEXT_PUBLIC_AGGREGATOR_ENABLED = false; // Enables or disables the aggregator
export const NEXT_PUBLIC_SOROSWAP_BACKEND_API_KEY = 'BACKEND_API_KEY'; // The API key to autenthicate in the soroswap backend
export const NEXT_PUBLIC_TRUSTLINE_WALLET_PUBLIC_KEY = 'STELLAR_PUBLIC_KEY'; // The public key of the trustline wallet
export const NEXT_PUBLIC_TEST_TOKENS_ADMIN_SECRET_KEY = 'STELLAR_SECRET_KEY'; // The secret key of the test tokens admin

export const NEXT_PUBLIC_BACKSTOP = 'CDAHGLVE6AZMXEGC22MV4GHU33REUJ5I5EJDIDHORQAVXVF64EIIK7QM';
export const NEXT_PUBLIC_BACKSTOP_V2 = 'CDAHGLVE6AZMXEGC22MV4GHU33REUJ5I5EJDIDHORQAVXVF64EIIK7QM';
export const NEXT_PUBLIC_POOL = 'CBZIQE2SZY5UW2THVQ2JAQHE3AKQLGSG7KX2GMGHTRVGQMBSJRXXCWCX';
export const NEXT_PUBLIC_COLLATERAL_ASSET = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';
export const NEXT_PUBLIC_STABLECOIN_ASSET = 'CDP4J3XSDKYI6DR4IJMJ7YSJA6KN23YWFRRWBQCI3DP3RHR6GBN3BB6I';
export const NEXT_PUBLIC_ROUTER_ID = 'CACIQ6HWPBEMPQYKRRAZSM6ZQORTBTS7DNXCRTI6NQYMUP2BHOXTBUVD';

export const NEXT_PUBLIC_USDC_ISSUER = 'GCAA2HBEFR7JWYZAVZ4HRZRMT3P6EVGI63HPUCSWIT37AMNXGJ5IKFXW';
export const NEXT_PUBLIC_BLND_ISSUER = 'GCAA2HBEFR7JWYZAVZ4HRZRMT3P6EVGI63HPUCSWIT37AMNXGJ5IKFXW';

export const NEXT_PUBLIC_PASSPHRASE = undefined
export const NEXT_PUBLIC_STELLAR_EXPERT_URL = undefined
export const  NEXT_PUBLIC_RPC_URL = undefined
export const NEXT_PUBLIC_HORIZON_URL = undefined